//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/UXAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UXAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UXAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UXAction"",
    ""maps"": [
        {
            ""name"": ""State"",
            ""id"": ""bceb96b5-8896-451f-a3fb-3afbc0d1acee"",
            ""actions"": [
                {
                    ""name"": ""Quit Game"",
                    ""type"": ""Button"",
                    ""id"": ""11c664b7-81b3-4bec-914d-0ed89ba4cfc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0907f4f9-528c-495b-bad2-8fe2cb5e5acd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // State
        m_State = asset.FindActionMap("State", throwIfNotFound: true);
        m_State_QuitGame = m_State.FindAction("Quit Game", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // State
    private readonly InputActionMap m_State;
    private IStateActions m_StateActionsCallbackInterface;
    private readonly InputAction m_State_QuitGame;
    public struct StateActions
    {
        private @UXAction m_Wrapper;
        public StateActions(@UXAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @QuitGame => m_Wrapper.m_State_QuitGame;
        public InputActionMap Get() { return m_Wrapper.m_State; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StateActions set) { return set.Get(); }
        public void SetCallbacks(IStateActions instance)
        {
            if (m_Wrapper.m_StateActionsCallbackInterface != null)
            {
                @QuitGame.started -= m_Wrapper.m_StateActionsCallbackInterface.OnQuitGame;
                @QuitGame.performed -= m_Wrapper.m_StateActionsCallbackInterface.OnQuitGame;
                @QuitGame.canceled -= m_Wrapper.m_StateActionsCallbackInterface.OnQuitGame;
            }
            m_Wrapper.m_StateActionsCallbackInterface = instance;
            if (instance != null)
            {
                @QuitGame.started += instance.OnQuitGame;
                @QuitGame.performed += instance.OnQuitGame;
                @QuitGame.canceled += instance.OnQuitGame;
            }
        }
    }
    public StateActions @State => new StateActions(this);
    public interface IStateActions
    {
        void OnQuitGame(InputAction.CallbackContext context);
    }
}
